interface FE {
    autresContributeurs: null | string;
    autresGES: null | string;
    cH4b: null | string;
    cH4f: null | string;
    cO2b: null | string;
    cO2f: null | string;
    codedelacatgorie: string;
    codegazsupplmentaire1: null | string;
    codegazsupplmentaire2: null | string;
    codegazsupplmentaire3: null | string;
    codegazsupplmentaire4: null | string;
    codegazsupplmentaire5: null | string;
    commentaireanglais: null | string;
    commentaireespagnol: null | string;
    commentairefranais: null | string;
    contributeur: null | string;
    datedecration: string;
    datedemodification: string;
    identifiantdellment: number;
    incertitude: null | string;
    localisationgographique: string;
    n2O: null | string;
    nomattributanglais: string;
    nomattributespagnol: null | string;
    nomattributfranais: null | string;
    nombaseanglais: string;
    nombaseespagnol: null | string;
    nombasefranais: string;
    nomfrontireanglais: null | string;
    nomfrontireespagnol: null | string;
    nomfrontirefranais: null | string;
    nomposteanglais: null | string;
    nomposteespagnol: null | string;
    nompostefranais: null | string;
    priodedevalidit: string;
    programme: string;
    qualit: string | null;
    qualitC: null | string;
    qualitGR: null | string;
    qualitM: null | string;
    qualitP: null | string;
    qualitTeR: number;
    qualitTiR: null | string;
    rglementations: null | string;
    source: string;
    souslocalisationgographiqueanglais: null | string;
    souslocalisationgographiqueespagnol: null | string;
    souslocalisationgographiquefranais: null | string;
    statutdellment: string;
    structure: string;
    tagsanglais: string;
    tagsespagnol: null | string;
    tagsfranais: string;
    totalpostenondcompos: string;
    transparence: number;
    typeLigne: string;
    typedellment: string;
    typeposte: null | string;
    unitanglais: string;
    unitespagnol: null | string;
    unitfranais: string;
    urlduprogramme: string;
    valeurgazsupplmentaire1: null | string;
    valeurgazsupplmentaire2: null | string;
    valeurgazsupplmentaire3: null | string;
    valeurgazsupplmentaire4: null | string;
    valeurgazsupplmentaire5: null | string;
  }
  