import { DataToFill } from '../types/DataToFill'

export const useDataToFill = () => {
  const dataToFill: DataToFill[] = [
    {
      id: 1,
      category: 'fuel',
      type: 'table',
      titleSelectInput: 'kindOfFuel',
      titleAnnualConsumptionInput: 'annualConsumption',
      tableHeader: ['typeOfFuel', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 2,
      category: 'electricity',
      type: 'calendar',
      titleSelectInput: 'billOfTheMonth',
      titleAnnualConsumptionInput: 'consumptionFromLatestBill',
      tableHeader: ['billOfTheMonth', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 3,
      category: 'advanced',
      type: 'table',
      titleSelectInput: 'kindOfGas',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['bunsenBurnerGas', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 4,
      category: 'food',
      type: 'table',
      titleSelectInput: 'foodService',
      tooltipText: 'foodTootlipText',
      titleAnnualConsumptionInput: 'meals',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 5,
      category: 'food',
      type: 'table',
      titleSelectInput: 'foodService',
      titleAnnualConsumptionInput: 'meals',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 6,
      category: 'food',
      type: 'table',
      titleSelectInput: 'foodService',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 7,
      category: 'school-buses',
      type: 'table',
      titleSelectInput: 'meanOfTravel',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 8,
      category: 'staff-travel',
      type: 'table',
      titleSelectInput: 'meanOfTravel',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 9,
      category: 'personnelTravel',
      type: 'table',
      titleSelectInput: 'meanOfTravel',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 10,
      category: 'schoolTrips',
      type: 'table',
      titleSelectInput: 'schoolTrips',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 11,
      category: 'furnitures',
      type: 'input',
      titleSelectInput: 'kindOfEmissionFactor',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 12,
      category: 'supplies',
      type: 'input',
      titleSelectInput: 'kindOfEmissionFactor',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 13,
      category: 'equipment',
      type: 'table',
      titleSelectInput: 'kindOfEmissionFactor',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 14,
      category: 'building',
      type: 'input',
      titleSelectInput: 'kindOfInfrastructure',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 15,
      category: 'equipment',
      type: 'input',
      titleSelectInput: 'kindOfEmissionFactor',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 16,
      category: 'equipment',
      type: 'input',
      titleSelectInput: 'kindOfEmissionFactor',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 17,
      category: 'equipment',
      type: 'input',
      titleSelectInput: 'kindOfEmissionFactor',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 18,
      category: 'equipment',
      type: 'input',
      titleSelectInput: 'kindOfEmissionFactor',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
    {
      id: 19,
      category: 'equipment',
      type: 'input',
      titleSelectInput: 'kindOfEmissionFactor',
      titleAnnualConsumptionInput: 'quantity',
      tableHeader: ['emissionFactor', 'quantity', 'value', 'uncertainty', 'total'],
    },
  ]

  return dataToFill
}
