-- CreateEnum
CREATE TYPE "Unit" AS ENUM ('A4_SHEET_100', 'KM_100', 'ACTIVE', 'APPAREL', 'RACE_KM', 'EURO_SPENT', 'FRANC_CFP', 'GJ_PCI', 'GJ_PCS', 'HA', 'HA_YEAR', 'HA_CLEMENTINE', 'HOUR', 'KEURO', 'KG', 'KG_BIOGNC', 'KG_NITROGEN_SPREAD', 'KG_DCO_REMOVED', 'KG_BIOWASTE', 'KG_SOFT_WHEAT_15', 'KG_TREATED_LEATHER', 'KG_FABA_BEAN_15', 'KG_GREEN_COFFEE_BEANS_NO_PULP', 'KG_RAPESEED_9', 'KG_WOOL', 'KG_MILK', 'KG_CORN_28', 'KG_ACTIVE_MATERIAL', 'KG_RAW_MATERIAL', 'KG_RAW_MATERIAL_12', 'KG_RAW_MATERIAL_15', 'KG_RAW_MATERIAL_74', 'KG_RAW_MATERIAL_80', 'KG_RAW_MATERIAL_9', 'KG_RAW_MATERIAL_16_SUGAR', 'KG_RAW_MATERIAL_NO_PULP', 'KG_DRY_MATTER', 'KG_NET_WEIGHT', 'KG_LIVE_WEIGHT', 'KG_LIVE_WEIGHT_CAT_0', 'KG_LIVE_WEIGHT_CAT_1', 'KG_LIVE_WEIGHT_CAT_2', 'KG_LIVE_WEIGHT_CAT_3', 'KG_SPRING_PEAS_15', 'KG_POTATO_80', 'KG_STARCH_POTATO_74', 'KG_TRITICALE_15', 'KG_NET_COMMERCIALLY_VIABLE_MEAT', 'KG_PASTURED_GRASS_80', 'KG_INGREDIENT_EXIT_STORE_NET_WEIGHT', 'KG_INGREDIENT_EXIT_STORE_NET_WEIGHT_GR', 'KG_INGREDIENT_EXIT_STORE_NET_WEIGHT_GRAINS', 'KG_INGESTED_INGREDIENT', 'KG_EGG', 'KG_EGG_CAT_0', 'KG_EGG_CAT_1', 'KG_EGG_CAT_2', 'KG_EGG_CAT_3', 'KG_BREWING_BARLEY_15', 'KG_FEED_BARLEY_15', 'KGH2', 'KG_MILK_LIQUID', 'KG_NTK', 'KM', 'KM_PERSON', 'KWH', 'KWH_PCI', 'KWH_PCS', 'LITER', 'LITER_LIQUID', 'POUND', 'METER', 'M2_SHON', 'M3', 'M3_KM', 'M3_N', 'METER_ROAD', 'MJ_PCI', 'ML', 'M2', 'M2_WALL', 'M2_FLOOR', 'M2_ROOF', 'PASSENGER_KM', 'PEQ_KM', 'PERSON_MONTH', 'UNIT_PIECE_SHRUB_POT', 'UNIT_PIECE_SHRUB_POT_3L', 'UNIT_PIECE_GRAFT', 'UNIT_PIECE_STEM', 'PORTION', 'MEAL', 'T', 'TEP', 'TEP_PCI', 'TEP_PCS', 'TON_KM', 'TON', 'TON_WITH_BONES', 'TON_RAW', 'TON_COLLECTED', 'TON_CLINKER', 'TON_WASTE', 'TON_K2O', 'TON_DRY_MATTER', 'TON_N', 'TON_P2O5', 'TON_VIABLE_MEAT', 'TON_KM_PRODUCED', 'TON_PRODUCTED', 'TON_PROCESSED', 'UNIT', 'IMPORTED_UNIT_PIECE_SHRUB_POT', 'VEHICLE_YEAR', 'VEHICLE_KM', 'CAR_KM', 'PERCENT', 'GJ_PER_TON', 'TON_KM_ROAD_PER_PERSON_YEAR', 'KG_FLUID', 'KWH_PER_HOME_YEAR', 'KM_PER_PERSON_YEAR', 'KGN_PER_HA', 'KWH_PER_M2_YEAR', 'GWH', 'KG_FLUID_PER_KW_FRIDGE', 'KG_FLUID_PER_m2', 'KG_FLUID_PER_EQUIPMENT', 'KG_FUILD_PER_STORAGE_M3', 'KWH_PER_HOUSING_YEAR', 'PERCENT_APPARTMENTS', 'PERCENT_HOUSES', 'DAY', 'LITER_PER_HA', 'MJ_PER_HA', 'KWH_PER_PERSON_FLOOR_YEAR', 'PLANT', 'KG_PER_m3', 'KGDBO', 'KGDBO_PER_M3', 'KG_H2_PER_100KM');

-- AlterTable
ALTER TABLE "groups" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "schools" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "session_emission_categories" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "session_emission_sub_categories" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "session_emissions" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "session_students" ALTER COLUMN "id" DROP DEFAULT;

-- AddForeignKey
ALTER TABLE "session_emission_categories" ADD CONSTRAINT "session_emission_categories_id_session_student_fkey" FOREIGN KEY ("id_session_student") REFERENCES "session_students"("id") ON DELETE SET NULL ON UPDATE CASCADE;
